let id = 0

export const clothes = [
  { id: id++, text: "Badeanzüge/ Bikini/ Badeshorts", done: false },
  { id: id++, text: "Shorts", done: false },
  { id: id++, text: "Gürtel (bei Bedarf)", done: false },
  { id: id++, text: "ggf. Kleider u. Rücke", done: false },
  { id: id++, text: "T-shirts, Tops", done: false },
  { id: id++, text: "lange Hose",done: false },
  { id: id++, text: "ein Pullover oder eine Strickjacke",done: false },
  { id: id++, text: "(Regen-)jacke",done: false },
  { id: id++, text: "Unterwäsche",done: false },
  { id: id++, text: "Socken",done: false },
  { id: id++, text: "Schlafanzug",done: false },
  { id: id++, text: "Brille",done: false },
  { id: id++, text: "Sonnenbrille",done: false },
  { id: id++, text: "Hut (als Sonnenschutz)",done: false },
  { id: id++, text: "Schuhe",done: false },
  { id: id++, text: "Kopfkissen",done: false },
  { id: id++, text: "Regenschirm",done: false },
  { id: id++, text: "Schmuck",done: false },
  { id: id++, text: "Handtasche",done: false },
]

export const valuables = [
  { id: id++, text: "Kreditkarte", done: false },
  { id: id++, text: "Geldbeute",done: false },
  { id: id++, text: "Bargeld",done: false },
  { id: id++, text: "Personalausweis/Reisepass",done: false },
  { id: id++, text: "Führerschein",done: false },
  { id: id++, text: "Ladekabel",done: false },
  { id: id++, text: "Powerbank",done: false },
  { id: id++, text: "Kopfhörer",done: false },
  { id: id++, text: "Buch",done: false },
  { id: id++, text: "Kamera",done: false },
]

export const hygiene = [
  { id: id++, text: "Zahnbürste",done: false },
  { id: id++, text: "Zahlpasta",done: false },
  { id: id++, text: "Deo",done: false },
  { id: id++, text: "Duschgel",done: false },
  { id: id++, text: "Shampoo",done: false },
  { id: id++, text: "Spühlung",done: false },
  { id: id++, text: "Rasierer",done: false },
  { id: id++, text: "Creme",done: false },
  { id: id++, text: "Sonnencreme",done: false },
  { id: id++, text: "Insektenspray",done: false },
  { id: id++, text: "Abschminkzeug",done: false },
  { id: id++, text: "Bürste",done: false },
  { id: id++, text: "Haargummi",done: false },
  { id: id++, text: "Damenhygieneartikel",done: false },
  { id: id++, text: "Strandtücher",done: false },
  { id: id++, text: "Desinfektionsmittel",done: false },
  { id: id++, text: "Kontaktlinsen",done: false },
  { id: id++, text: "Medikamente",done: false },
  { id: id++, text: "Bonbons (Fisherman's)",done: false },
  { id: id++, text: "Tempos",done: false },
]
