export const clothes = [
  "Badeanzüge/ Bikini/ Badeshorts",
  "Shorts",
  "Gürtel (bei Bedarf)",
  "ggf. Kleider u. Rücke",
  "T-shirts, Tops",
  "lange Hose",
  "ein Pullover oder eine Strickjacke",
  "(Regen-)jacke",
  "Unterwäsche",
  "Socken",
  "Schlafanzug",
  "Brille",
  "Sonnenbrille",
  "Hut (als Sonnenschutz)",
  "Schuhe",
  "Kopfkissen",
  "Regenschirm",
  "Schmuck",
  "Handtasche",
]

export const valuables = [
  "Kreditkarte",
  "Geldbeute",
  "Bargeld",
  "Personalausweis/Reisepass",
  "Führerschein",
  "Ladekabel",
  "Powerbank",
  "Kopfhörer",
  "Buch",
  "Kamera",
]

export const hygiene = [
  "Zahnbürste",
  "Zahlpasta",
  "Deo",
  "Duschgel",
  "Shampoo",
  "Spühlung",
  "Rasierer",
  "Creme",
  "Sonnencreme",
  "Insektenspray",
  "Abschminkzeug",
  "Bürste",
  "Haargummi",
  "Damenhygieneartikel",
  "Strandtücher",
  "Desinfektionsmittel",
  "Kontaktlinsen",
  "Medikamente",
  "Bonbons (Fisherman's)",
  "Tempos",
]
